# dpi-aware=no
hide-before-typing=yes
fields=name,generic,comment,categories,filename,keywords
font="0xProto Nerd Font":weight=bold:size=24
prompt="❯   "
line-height=36
width=50
vertical-pad=16
horizontal-pad=32
inner-pad=16

[colors]
background=080d36ff
text=4a5472ff
match=fc01ffff
selection=303958ff
selection-text=f7f7f7ff
selection-match=24fcfcff
prompt=ffff16ff
input=f7f7f7ff
border=4a5472ff

[border]
width=4
radius=20
selection-radius=10

[dmenu]
exit-immediately-if-empty=yes
